#!/usr/bin/env php
<?php

use Minicli\App;

if (php_sapi_name() !== "cli") {
  exit;
}

require __DIR__ . "/config/bootstrap.php";

$container = require __DIR__ . "/config/container.php";

(new App($container))->run($argv);
